# docker-compose.yml
version: '3'

services:
  nginx:
     image: nginx:latest
     container_name: ng
     ports:
       - "8000:8000"
     volumes:
       - ./config/nginx:/etc/nginx/conf.d
     depends_on:
       - web
  web:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/symfony
    command: bash -c "cd /symfony && cd foyer && composer update && php bin/console server:run 0.0.0.0:8000"
  db:
    image: postgres:latest
    container_name: ps
