#index:
#    path: /
#    controller: App\Controller\DefaultController::index

dashboard:
    path: /
    defaults:
        _controller: App\Controller\DashboardController::index

platform_view:
    path: /advert/{id}
    defaults:
        _controller: App\Controller\DashboardController::view

platform_add:
    path: /add
    defaults:
        _controller: App\Controller\DashboardController::add

jsontest:
    path: /jsontest/{id}
    defaults:
        _controller: App\Controller\DashboardController::JSONtest
